### PR TITLE
Added documentation for React 16.3

### PR DESCRIPTION
**Pull request by charliearlie**
I use these cheat sheets quite a lot and noticed today that there's nothing in regards to React 16.3. As it's currently available in beta and is being used, I thought now should be the time to update this cheat sheet. 

I have added deprecation information for the lifecycle hooks `componentWillUpdate`, `componentWillReceiveProps` and `componentWillMount` with information on how to replace them. 

I have also added information on the 2 new lifecycle hooks and the polyfill that can be used to get these functions into older versions of React.

And finally, I added a small snippet on the React Context API.

### CODE REVIEW

**Comment by LeCoupa** [comment]
Thank you so much. I will merge it in a few hours (the plane is going to take off).

**Comment by charliearlie** [comment]
I just added a link to the Angular cheat sheet in the README as well. Not relevant to this PR but just thought as I'm adding stuff for the frontend.

**Comment by charliearlie** [comment]
So yeah... I'm closing this.

**Comment by LeCoupa** [comment]
Sorry, can you reopen it?

**Comment by charliearlie** [comment]
No need to apologise. I just closed it because I kept thinking i had a pull request open in another repo.

**Comment by charliearlie** [comment]
And I can no longer re-open it because the fork I had has been deleted. I'll do it again some time this week.

**Comment by LeCoupa** [comment]
Thank you and sorry for the delay!

**Pull request closed without merging**
