### PR TITLE
Express Cheatsheets

### PR DESCRIPTION
**Pull request by ZohebMOPO**
Added Express Cheatsheets @LeCoupa

### CODE REVIEW

**Comment by LeCoupa** [comment]
Great, can you add the link to the readme? (alphabetical order)

**Comment by ZohebMOPO** [comment]
Yeah sure

**Comment by ZohebMOPO** [comment]
Hey @LeCoupa,
I just added that in Readme.md. If anything more I need to do just let me know.

**Comment by bwilleyiv** [comment]
Cool

**Pull request merged**
