### PR TITLE
Adding Ruby Cheat Sheet

### PR DESCRIPTION
**Pull request by elliotfayman**
I have added a cheat sheet for the key words in the ruby programming language.

### CODE REVIEW

**Review by WilderMO — CHANGES_REQUESTED** [review]
Please write the information in markdown.

**Review by WilderMO — APPROVED** [review]
looks good

**Comment by elliotfayman** [comment]
Sounds good! Do I have to do the final merge from my end or is that something that I don't have to worry about?

**Comment by WilderMO** [comment]
The final merge will be done by @LeCoupa. 
You just need to wait till he merges it.

**Comment by elliotfayman** [comment]
Ok got it. I have contributed to a few other projects, and I have noticed that this final step always takes a while, so I wanted to double check.

**Review by WilderMO — APPROVED** [review]
looks good

**Pull request closed without merging**
