### PR TITLE
Cheatsheet for Vim

### PR DESCRIPTION
**Pull request by lucifer069**

### CODE REVIEW

**Comment by LeCoupa** [comment]
Thank you so much! I'm currently far away from my computer. I will merge tonight :-)

**Comment by LeCoupa** [comment]
Thank you again!

**Comment by LeCoupa** [comment]
Hello Lucifer, your cheatsheet is trending! :)

https://www.reddit.com/r/vim/comments/7vkenp/vim_cheatsheet_everything_you_should_know_in_one/

**Comment by lucifer069** [comment]
Happy to contribute, Julien
I am Prateek,by the way


On Tue, Feb 6, 2018 at 5:02 PM, Julien Le Coupanec <notifications@github.com

**Comment by LeCoupa** [comment]
Nice to meet you :-)

**Pull request merged**
