### PR TITLE
Add Go language

### PR DESCRIPTION
**Pull request by LuanSilveiraSouza**
Hello! I created a cheatsheet for the Go language. It is almost complete, only lacking of more examples of standard libs and concurrence, but I pretend to finish so I'm already submitting this PR. 
I Hope it helps the project!

### CODE REVIEW

**Comment by LeCoupa** [comment]
Great @LuanSilveiraSouza :) can you update the README file? :)

**Comment by LuanSilveiraSouza** [comment]
> Great @LuanSilveiraSouza :) can you update the README file? :)

Done! I added concurrency too, for a first version I think its complete :D.
If you need anything more to match the repository patterns, just tell me. Thanks!

**Comment by LeCoupa** [comment]
Thank you @LuanSilveiraSouza  :)

**Comment by LeCoupa** [comment]
I have also submitted your cheatsheet to Reddit https://www.reddit.com/r/golang/ :)

**Review by Jsn2win — COMMENTED** [review]
Almost done

**Pull request merged**
