### PR TITLE
JavaScript language Objects section creation

### PR DESCRIPTION
**Pull request by stmoreau**
Hi @LeCoupa, good work on that project!

The sum of my work on that repo is the following:
- fixed a couple of whitespace issues in the `README.md`
- restructured the files for javascript language. As a js lover I see myself contributing to that repo (mainly in the javascript section) so it's nice to have it be a bit more scalable
- added `objects` file in `javascript` directory following the set convention using as a resource https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object
- added my company's logo in the `README.md` as you suggested 😉

Keep up the good work and thank you for contributing to the community in this way! 💯

### CODE REVIEW

**Comment by stmoreau** [comment]
@dancyfits don't believe your commit has anything to do with that PR.

@LeCoupa please have a look and consider that 🥇

**Comment by dancyfits** [comment]
@stmoreau accidentally put #46 but I thought I corrected it to #43.  I'll check again; sorry for the confusion!

**Comment by LeCoupa** [comment]
@stmoreau Thank you for the PR :)

Can you keep the javascript cheatsheet into one single file so I can merge it.

**Comment by stmoreau** [comment]
There you go @LeCoupa! 
Happy for you to merge :bowtie:

**Comment by LeCoupa** [comment]
Thank you so much! Happy to work with you 😁 

I just joined a new company last month so I was kind of busy. :)

**Comment by stmoreau** [comment]
No worries @LeCoupa! Glad you got the time.

Hope your new company treats you well !

**Pull request merged**
