### PR TITLE
Ember cheatsheet

### LINKED ISSUE #41: Ember cheatsheet
Would love to get an Ember cheatsheet in the mix!

### PR DESCRIPTION
**Pull request by yohanmishkin**
Closes #41

### CODE REVIEW

**Comment by LeCoupa** [comment]
So cool! I will merge tomorrow when I wake up :)

**Comment by yohanmishkin** [comment]
Hiya! Might it be possible to merge this?

**Comment by yohanmishkin** [comment]
Hey @LeCoupa, anything I can to do to help get this over the finish-line?

**Comment by LeCoupa** [comment]
Thank you so much!

**Comment by yohanmishkin** [comment]
Thanks for the merge!

**Pull request merged**
