### PR TITLE
added rm -f in docker.sh

### PR DESCRIPTION
**Pull request by mhemanthkmr**
Kindly Verify it

### CODE REVIEW

**Comment by LeCoupa** [comment]
Thank you!

**Comment by mhemanthkmr** [comment]
> 

Can you send a tip for me ?

**Comment by LeCoupa** [comment]
A tip for one line changed? 😅

**Comment by mhemanthkmr** [comment]
Hii @LeCoupa where is the index.html file I searched I can't find it.

**Pull request merged**
