### PR TITLE
docs(gsap.pdf): create cheatsheet for GreenSock

### PR DESCRIPTION
**Pull request by wise-introvert**
original source: https://ihatetomatoes.net/wp-content/uploads/2016/07/GreenSock-Cheatsheet-4.pdf

### CODE REVIEW

**Comment by LeCoupa** [comment]
Sorry no PDF

**Comment by wise-introvert** [comment]
Okay, no problem. What format should I use. Can you please point me to the documentation.

Thanks!

**Comment by LeCoupa** [comment]
Something similar to this :) https://github.com/LeCoupa/awesome-cheatsheets/blob/master/backend/node.js

**Comment by wise-introvert** [comment]
Okay. Thanks a ton!

**Pull request closed without merging**
